# Generated by Django 5.0.3 on 2024-06-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reset_code", models.CharField(max_length=16)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("used", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
