# Generated by Django 5.0.3 on 2024-06-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordreset",
            old_name="used",
            new_name="valid",
        ),
    ]
