# Generated by Django 5.0.3 on 2024-06-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_used_passwordreset_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordreset",
            name="valid",
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="invalidated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
