version: "3"
services:
  postgres:
    image: postgres:16.3
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
      - "POSTGRES_USER=${POSTGRES_USER:-postgres}"
      - "POSTGRES_DB=${POSTGRES_DB:-postgres}"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
