from django.db import models
from django.utils.translation import gettext_lazy as _


class PoliticalParty(models.TextChoices):
    DEMOCRATIC = "democratic", _("Democratic Party")
    REPUBLICAN = "republican", _("Republican Party")
    INDEPENDENT = "independent", _("Independent")
    LIBERTARIAN = "libertarian", _("Libertarian Party")
    FORWARD = "forward", _("Forward")
    VERMONT_PROGRESSIVE = "vermont_progressive", _("Vermont Progressive Party")
    INDEPENDENT_OF_OREGON = "independent_of_OREGON", _("Independent Party of Oregon")
    GREEN = "green", _("Green party")
    CONSTITUTION = "constitution", _("Constitution Party")
    WORKING_FAMILIES = "working_families", _("Working Families Party")
    ALLIANCE = "alliance", _("alliance Party")
    REFORM = "reform", _("reform Party")
    WORKING_CLASS = "working_class", _("Working Class Party")
    SOCIALISM_LIBERATION = "socialism_liberation", _("Party for Socialism and Liberation")
    AMERICAN_INDEPENDENT = "american_independent_party", _("American Independent Party")
    PEACE_FREEDOM = "peace_freedom", _("Peace and Freedom Party")
    SOLIDARITY = "solidarity", _("american Solidarity Party")
    LEGAL_MARIJUANA = "legal_marijuana", _("Legal Marijuana Now Party")
    UNITY_PARTY = "unity_party", _("unity Party")
    NATURAL_LAW = "natural_law", _("natural Law Party")
    APPROVAL_VOTING = "approval_voting", _("Approval Voting Party")
    JUSTICE = "justice", _("justice Party")
    PEOPLE = "people", _("People's Party")
    COLORADO_CENTER = "colorado_center", _("Colorado Center Party")
    CONSERVATIVE_NY = "conservative_ny", _("Conservative Party of New York State")
    LIBERTARIAN_MASS = "libertarian_mass", _("Libertarian Association of Massachusetts")
    LIBERTARIRAN_NM = "libertarian_nm", _("Libertarian Party of New Mexico")
    OREGON_PROGRESSIVE = "oregon_progressive", _("Oregon Progressive Party")
    GREEN_MOUNTAIN = "green_mountain", _("Green Mountain Peace and Justice Party")
    ALASKAN_INDEPENDENCE = "alaskan_independence", _("Alaskan Independence Party")
    INDEPENDENT_DELAWARE = "independent_delaware", _("Independent Party of Delaware")
    UNITED_UTAH = "united_utah", _("united Utah Party")
    ECOLOGY_FLORIDA = "ecology_florida", _("Ecology Party of Florida")
    INDEPENDENT_FLORIDA = "independent_florida", _("Independent Party of Florida")
    ALOHA = "aloha", _("Aloha party")
    GRASSROOTS_CANNABIS = "grassroots_CANNABIS", _("Grassroots - Legalize Cannabis Party")
    LABOR = "labor", _("Labor party")
    UNITED_CITIZENS = "united_citizens", _("United Citizens Party")
    INDEPENDENT_CITIZENS = "independent_citizens", _("Independent Citizens Movement")
    SOVEREIGN_UNION = "sovereign_union", _("Sovereign Union Movement")
    SOCIALIST_WORKERS = "socialist_workers", _("Socialist Workers Party")
    PROHIBITION = "prohibition", _("Prohibition Party")
    SOCIALIST_EQUALITY = "socialist_equality", _("Socialist Equality Party")
    SOCIALIST_USA = "socialist_usa", _("Socialist Party USA")
    COMMUNIST = "communist", _("communist Party USA")
    PROGRESSIVE_LABOR = "progressive_labor", _("Progressive Labor Party")
    SOCIALIST_ALTERNATIVE = "socialist_alternative", _("Socialist Alternative")
    PIRATE = "pirate", _("United states Pirate Party")
    WORKERS_WORLD = "workers_world", _("Workers World Party")
    FREEDOM_SOCIALIST = "freedom_socialist", _("Freedom Socialist Party")
    AMERICAN_FREEDOM = "american_freedom", _("American Freedom Party")
    SOCIALIST_ACTION = "socialist_action", _("Socialist Action")
    TRANSHUMANIST = "transhumanist", _("Transhumanist Party")
