from django.db import models
from django.utils.translation import gettext_lazy as _


class PoliticalParty(models.TextChoices):
    DEMOCRATIC = "DEMOCRATIC", _("Democratic Party")
    REPUBLICAN = "REPUBLICAN", _("Republican Party")
    INDEPENDENT = "INDEPENDENT", _("Independent")
    LIBERTARIAN = "LIBERTARIAN", _("Libertarian Party")
    FORWARD = "FORWARD", _("Forward")
    VERMONT_PROGRESSIVE = "VERMONT_PROGRESSIVE", _("Vermont Progressive Party")
    INDEPENDENT_OF_OREGON = "INDEPENDENT_OF_OREGON", _("Independent Party of Oregon")
    GREEN = "GREEN", _("Green Party")
    CONSTITUTION = "CONSTITUTION", _("Constitution Party")
    WORKING_FAMILIES = "WORKING_FAMILIES", _("Working Families Party")
    ALLIANCE = "ALLIANCE", _("Alliance Party")
    REFORM = "REFORM", _("Reform Party")
    WORKING_CLASS = "WORKING_CLASS", _("Working Class Party")
    SOCIALISM_LIBERATION = "SOCIALISM_LIBERATION", _("Party for Socialism and Liberation")
    AMERICAN_INDEPENDENT = "AMERICAN_INDEPENDENT_PARTY", _("American Independent Party")
    PEACE_FREEDOM = "PEACE_FREEDOM", _("Peace and Freedom Party")
    SOLIDARITY = "SOLIDARITY", _("American Solidarity Party")
    LEGAL_MARIJUANA = "LEGAL_MARIJUANA", _("Legal Marijuana Now Party")
    UNITY_PARTY = "UNITY_PARTY", _("Unity Party")
    NATURAL_LAW = "NATURAL_LAW", _("Natural Law Party")
    APPROVAL_VOTING = "APPROVAL_VOTING", _("Approval Voting Party")
    JUSTICE = "JUSTICE", _("Justice Party")
    PEOPLE = "PEOPLE", _("People's Party")
    COLORADO_CENTER = "COLORADO_CENTER", _("Colorado Center Party")
    CONSERVATIVE_NY = "CONSERVATIVE_NY", _("Conservative Party of New York State")
    LIBERTARIAN_MASS = "LIBERTARIAN_MASS", _("Libertarian Association of Massachusetts")
    LIBERTARIRAN_NM = "LIBERTARIAN_NM", _("Libertarian Party of New Mexico")
    OREGON_PROGRESSIVE = "OREGON_PROGRESSIVE", _("Oregon Progressive Party")
    GREEN_MOUNTAIN = "GREEN_MOUNTAIN", _("Green Mountain Peace and Justice Party")
    ALASKAN_INDEPENDENCE = "ALASKAN_INDEPENDENCE", _("Alaskan Independence Party")
    INDEPENDENT_DELAWARE = "INDEPENDENT_DELAWARE", _("Independent Party of Delaware")
    UNITED_UTAH = "UNITED_UTAH", _("United Utah Party")
    ECOLOGY_FLORIDA = "ECOLOGY_FLORIDA", _("Ecology Party of Florida")
    INDEPENDENT_FLORIDA = "INDEPENDENT_FLORIDA", _("Independent Party of Florida")
    ALOHA = "ALOHA", _("Aloha Party")
    GRASSROOTS_CANNABIS = "GRASSROOTS_CANNABIS", _("Grassroots - Legalize Cannabis Party")
    LABOR = "LABOR", _("Labor Party")
    UNITED_CITIZENS = "UNITED_CITIZENS", _("United Citizens Party")
    INDEPENDENT_CITIZENS = "INDEPENDENT_CITIZENS", _("Independent Citizens Movement")
    SOVEREIGN_UNION = "SOVEREIGN_UNION", _("Sovereign Union Movement")
    SOCIALIST_WORKERS = "SOCIALIST_WORKERS", _("Socialist Workers Party")
    PROHIBITION = "PROHIBITION", _("Prohibition Party")
    SOCIALIST_EQUALITY = "SOCIALIST_EQUALITY", _("Socialist Equality Party")
    SOCIALIST_USA = "SOCIALIST_USA", _("Socialist Party USA")
    COMMUNIST = "COMMUNIST", _("Communist Party USA")
    PROGRESSIVE_LABOR = "PROGRESSIVE_LABOR", _("Progressive Labor Party")
    SOCIALIST_ALTERNATIVE = "SOCIALIST_ALTERNATIVE", _("Socialist Alternative")
    PIRATE = "PIRATE", _("United States Pirate Party")
    WORKERS_WORLD = "WORKERS_WORLD", _("Workers World Party")
    FREEDOM_SOCIALIST = "FREEDOM_SOCIALIST", _("Freedom Socialist Party")
    AMERICAN_FREEDOM = "AMERICAN_FREEDOM", _("American Freedom Party")
    SOCIALIST_ACTION = "SOCIALIST_ACTION", _("Socialist Action")
    TRANSHUMANIST = "TRANSHUMANIST", _("Transhumanist Party")
