# Generated by Django 5.0.3 on 2024-03-18 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_alter_candidate_id_alter_candidaterace_id"),
        ("issue", "0002_voterissue"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateIssueQuestionOpinion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
                (
                    "issue_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="issue.issuequestion",
                    ),
                ),
            ],
        ),
    ]
