# Generated by Django 5.0.3 on 2024-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0003_candidateissuequestionopinion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateissuequestionopinion",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="voterissuequestionopinion",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
