# Generated by Django 5.0.3 on 2024-04-06 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0006_remove_candidate_days_served_candidate_start_date"),
        ("issue", "0004_alter_candidateissuequestionopinion_rating_and_more"),
        ("voter", "0003_voter_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateVector",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("immigration", models.FloatField(default=0.0)),
                ("environment", models.FloatField(default=0.0)),
                ("gun_control", models.FloatField(default=0.0)),
                ("abortion", models.FloatField(default=0.0)),
                ("healthcare", models.FloatField(default=0.0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoterVector",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("immigration", models.FloatField(default=0.0)),
                ("environment", models.FloatField(default=0.0)),
                ("gun_control", models.FloatField(default=0.0)),
                ("abortion", models.FloatField(default=0.0)),
                ("healthcare", models.FloatField(default=0.0)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voter.voter"
                    ),
                ),
            ],
        ),
    ]
