# Generated by Django 5.0.3 on 2024-04-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0005_candidatevector_votervector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votervector",
            name="voter",
        ),
        migrations.DeleteModel(
            name="CandidateVector",
        ),
        migrations.DeleteModel(
            name="VoterVector",
        ),
    ]
