# Generated by Django 5.0.3 on 2024-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0007_alter_voterissue_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voterissue",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
