# Generated by Django 5.0.3 on 2024-04-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0008_alter_voterissue_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.CharField(
                choices=[("social", "Social"), ("economic", "Economic")], max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="high_score_tendency",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")], max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="low_score_tendency",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")], max_length=64
            ),
        ),
    ]
