# Generated by Django 5.0.3 on 2024-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_alter_candidate_id_alter_candidaterace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_photo",
            field=models.URLField(default="https://test.com"),
            preserve_default=False,
        ),
    ]
