# Generated by Django 5.0.3 on 2024-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0004_alter_candidate_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="facebook",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="profile_photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="twitter",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="url",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
