# Generated by Django 5.0.3 on 2024-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0005_alter_candidate_facebook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="days_served",
        ),
        migrations.AddField(
            model_name="candidate",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
