# Generated by Django 5.0.6 on 2024-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_candidate_ethnicity_alter_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='political_party',
            field=models.CharField(choices=[('democratic', 'Democratic Party'), ('republican', 'Republican Party'), ('independent', 'Independent'), ('libertarian', 'Libertarian Party'), ('forward', 'Forward'), ('vermont_progressive', 'Vermont Progressive Party'), ('independent_of_OREGON', 'Independent Party of Oregon'), ('green', 'Green party'), ('constitution', 'Constitution Party'), ('working_families', 'Working Families Party'), ('alliance', 'alliance Party'), ('reform', 'reform Party'), ('working_class', 'Working Class Party'), ('socialism_liberation', 'Party for Socialism and Liberation'), ('american_independent_party', 'American Independent Party'), ('peace_freedom', 'Peace and Freedom Party'), ('solidarity', 'american Solidarity Party'), ('legal_marijuana', 'Legal Marijuana Now Party'), ('unity_party', 'unity Party'), ('natural_law', 'natural Law Party'), ('approval_voting', 'Approval Voting Party'), ('justice', 'justice Party'), ('people', "People's Party"), ('colorado_center', 'Colorado Center Party'), ('conservative_ny', 'Conservative Party of New York State'), ('libertarian_mass', 'Libertarian Association of Massachusetts'), ('libertarian_nm', 'Libertarian Party of New Mexico'), ('oregon_progressive', 'Oregon Progressive Party'), ('green_mountain', 'Green Mountain Peace and Justice Party'), ('alaskan_independence', 'Alaskan Independence Party'), ('independent_delaware', 'Independent Party of Delaware'), ('united_utah', 'united Utah Party'), ('ecology_florida', 'Ecology Party of Florida'), ('independent_florida', 'Independent Party of Florida'), ('aloha', 'Aloha party'), ('grassroots_CANNABIS', 'Grassroots - Legalize Cannabis Party'), ('labor', 'Labor party'), ('united_citizens', 'United Citizens Party'), ('independent_citizens', 'Independent Citizens Movement'), ('sovereign_union', 'Sovereign Union Movement'), ('socialist_workers', 'Socialist Workers Party'), ('prohibition', 'Prohibition Party'), ('socialist_equality', 'Socialist Equality Party'), ('socialist_usa', 'Socialist Party USA'), ('communist', 'communist Party USA'), ('progressive_labor', 'Progressive Labor Party'), ('socialist_alternative', 'Socialist Alternative'), ('pirate', 'United states Pirate Party'), ('workers_world', 'Workers World Party'), ('freedom_socialist', 'Freedom Socialist Party'), ('american_freedom', 'American Freedom Party'), ('socialist_action', 'Socialist Action'), ('transhumanist', 'Transhumanist Party'), ('choose_not_to_share', 'Choose not to share')], help_text='The party to which the candidate belongs. Independent, Republican, etc.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='candidaterace',
            name='race',
            field=models.CharField(choices=[('american_indian_or_alaska_native', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black_or_african_american', 'Black or African American'), ('native_hawaiian_or_pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('white', 'White'), ('choose_not_to_share', 'Choose not to share')], max_length=1024),
        ),
    ]
