apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yourballot-pvc
  namespace: ballot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
