environment: staging

image:
  repository: registry.peteherman.codes:31111/yourballot
  tag: latest
  pullPolicy: Always
  
api:
  replicaCount: 1
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  
ingress:
  className: haproxy
  # annotations:
  #   haproxy.org/ssl-passthrough: "true"

pvc:
  resources:
    requests:
      storage: 3Gi

nginx:
  repository: registry.peteherman.codes:31111/nginx
  tag: latest

  resources:
    requests:
      memory: "500Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
