# Generated by Django 5.0.3 on 2024-03-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoliticalLocality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1024)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TOWN", "Town"),
                            ("CITY", "City"),
                            ("STATE", "State"),
                            ("FEDERAL", "Federal"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
