# Generated by Django 5.0.3 on 2024-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locality", "0002_zipcodelocality"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicallocality",
            name="geo_json_id",
            field=models.UUIDField(null=True),
        ),
    ]
