# Generated by Django 5.0.3 on 2024-04-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locality", "0003_politicallocality_geo_json_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politicallocality",
            name="type",
            field=models.CharField(
                choices=[
                    ("town", "Town"),
                    ("city", "City"),
                    ("state", "State"),
                    ("federal", "Federal"),
                ],
                max_length=32,
            ),
        ),
    ]
