# Generated by Django 5.0.3 on 2024-03-20 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Minimum age is 1 year(s) old"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("HISPANIC_OR_LATINO", "Hispanic or Latino"),
                    ("NOT_HISPANIC_OR_LATINO", "Not Hispanic or Latino"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("Transgender", "Transgender"),
                    ("NONBINARY", "Nonbinary"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="political_identity",
            field=models.CharField(
                blank=True,
                help_text="The way a voter may describe themselves politically. e.g. a left-leaning moderate",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="political_party",
            field=models.CharField(
                choices=[
                    ("DEMOCRATIC", "Democratic Party"),
                    ("REPUBLICAN", "Republican Party"),
                    ("INDEPENDENT", "Independent"),
                    ("LIBERTARIAN", "Libertarian Party"),
                    ("FORWARD", "Forward"),
                    ("VERMONT_PROGRESSIVE", "Vermont Progressive Party"),
                    ("INDEPENDENT_OF_OREGON", "Independent Party of Oregon"),
                    ("GREEN", "Green Party"),
                    ("CONSTITUTION", "Constitution Party"),
                    ("WORKING_FAMILIES", "Working Families Party"),
                    ("ALLIANCE", "Alliance Party"),
                    ("REFORM", "Reform Party"),
                    ("WORKING_CLASS", "Working Class Party"),
                    ("SOCIALISM_LIBERATION", "Party for Socialism and Liberation"),
                    ("AMERICAN_INDEPENDENT_PARTY", "American Independent Party"),
                    ("PEACE_FREEDOM", "Peace and Freedom Party"),
                    ("SOLIDARITY", "American Solidarity Party"),
                    ("LEGAL_MARIJUANA", "Legal Marijuana Now Party"),
                    ("UNITY_PARTY", "Unity Party"),
                    ("NATURAL_LAW", "Natural Law Party"),
                    ("APPROVAL_VOTING", "Approval Voting Party"),
                    ("JUSTICE", "Justice Party"),
                    ("PEOPLE", "People's Party"),
                    ("COLORADO_CENTER", "Colorado Center Party"),
                    ("CONSERVATIVE_NY", "Conservative Party of New York State"),
                    ("LIBERTARIAN_MASS", "Libertarian Association of Massachusetts"),
                    ("LIBERTARIAN_NM", "Libertarian Party of New Mexico"),
                    ("OREGON_PROGRESSIVE", "Oregon Progressive Party"),
                    ("GREEN_MOUNTAIN", "Green Mountain Peace and Justice Party"),
                    ("ALASKAN_INDEPENDENCE", "Alaskan Independence Party"),
                    ("INDEPENDENT_DELAWARE", "Independent Party of Delaware"),
                    ("UNITED_UTAH", "United Utah Party"),
                    ("ECOLOGY_FLORIDA", "Ecology Party of Florida"),
                    ("INDEPENDENT_FLORIDA", "Independent Party of Florida"),
                    ("ALOHA", "Aloha Party"),
                    ("GRASSROOTS_CANNABIS", "Grassroots - Legalize Cannabis Party"),
                    ("LABOR", "Labor Party"),
                    ("UNITED_CITIZENS", "United Citizens Party"),
                    ("INDEPENDENT_CITIZENS", "Independent Citizens Movement"),
                    ("SOVEREIGN_UNION", "Sovereign Union Movement"),
                    ("SOCIALIST_WORKERS", "Socialist Workers Party"),
                    ("PROHIBITION", "Prohibition Party"),
                    ("SOCIALIST_EQUALITY", "Socialist Equality Party"),
                    ("SOCIALIST_USA", "Socialist Party USA"),
                    ("COMMUNIST", "Communist Party USA"),
                    ("PROGRESSIVE_LABOR", "Progressive Labor Party"),
                    ("SOCIALIST_ALTERNATIVE", "Socialist Alternative"),
                    ("PIRATE", "United States Pirate Party"),
                    ("WORKERS_WORLD", "Workers World Party"),
                    ("FREEDOM_SOCIALIST", "Freedom Socialist Party"),
                    ("AMERICAN_FREEDOM", "American Freedom Party"),
                    ("SOCIALIST_ACTION", "Socialist Action"),
                    ("TRANSHUMANIST", "Transhumanist Party"),
                ],
                help_text="The party to which the voter is registered. Independent, Republican, etc.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
