# Generated by Django 5.0.3 on 2024-04-11 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0004_alter_voter_ethnicity_alter_voter_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="zipcode",
            field=models.CharField(
                default=12831,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Zip code must be in the format XXXXX", regex="^\\d{5}$"
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
