# Generated by Django 5.0.3 on 2024-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0005_voter_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("Hispanic or Latino", "Hispanic Or Latino"),
                    ("Not Hispanic or Latino", "Not Hispanic Or Latino"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
