# Generated by Django 5.0.3 on 2024-06-01 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0009_alter_voter_ethnicity_alter_voter_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
