# Generated by Django 5.0.6 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_alter_voter_political_party_alter_voter_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender'), ('Nonbinary', 'Nonbinary'), ('Other', 'Other'), ('Choose not to share', 'Choose Not To Share')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='race',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian Or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black Or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian Or Pacific Islander'), ('White', 'White'), ('Choose not to share', 'Choose Not To Share')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voterrace',
            name='race',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian Or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black Or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian Or Pacific Islander'), ('White', 'White'), ('Choose not to share', 'Choose Not To Share')], max_length=1024),
        ),
    ]
